### ISSUE TITLE
need more details for report_batch.cc:78] Mixer Report failed with: UNAVAILABLE

### ISSUE THREAD

**Issue by ldemailly** [istio/mixerclient#106]
We see quite a lot of :

W0908 06:04:25.765] [libprotobuf ERROR external/mixerclient_git/src/report_batch.cc:78] Mixer Report failed with: UNAVAILABLE

eg https://k8s-gubernator.appspot.com/build/istio-prow/pull/istio_istio/699/e2e-suite-rbac-no_auth/360/

it would be great upon error to print which ip etc. we were connecting to and more details and granularity about the failure (did we fail to connect, did we timeout, did we not get a response, did we get a weird response, read error etc... (did we read anything, if so print that)

cc @mandarjog

**Comment by qiwzhang** [comment]
This is the gRPC call status.   Report [API](https://github.com/istio/api/blob/master/mixer/v1/report.proto) API did not return any response.  gRPC status could mean both network error or sever error.  UNAVAILABLE most likely from mixer server.

We don't know mixer IP.  Only Envoy cluster manager know.

**Comment by ldemailly** [comment]
Thanks !

is there some verbose or debug we can turn on for grpc c++ client to get more info for failure ?

are you sure there is nothing useful/printable in the response for instance (before delete) ?

sorry for silly question but how do we connect if we don't know to what ? is there a debug level in envoy that would print more info

**Comment by qiwzhang** [comment]
We are using Envoy gRPC async client code.   If debug is on, it may print more debug info.  

Mixer server ip is specified in "ClusterManager" in the envoy config generated by Pilot.  Again, Envoy gRPC async client code use it.  The caller just specifies the "cluster name".

**Comment by ldemailly** [comment]
funnily we still have that issue right now

**Comment by qiwzhang** [comment]
If the issue is that the Error should not be there, I think we need to check Mixer log.
