### ISSUE TITLE
httpFault/abort rules trigger does not send data to Prometheus

### ISSUE THREAD

**Issue by mandarjog** [istio/mixerclient#133]
@esnible commented on [Tue May 30 2017](https://github.com/istio/mixer/issues/769)

To reproduce, start up bookinfo.

```bash
cat << EOF |
type: route-rule
name: ratings-fail-xpercent
spec:
  destination: ratings.default.svc.cluster.local
  precedence: 2
  httpFault:
    abort:
      percent: 95
      httpStatus: 500
EOF
istioctl replace
```

Drive some traffic.  Then look at the output in Prometheus or ServiceGraph.  The traffic is reduced by the %, but there are no response_code entries for the injected 500s.

---

@ZackButcher commented on [Tue May 30 2017](https://github.com/istio/mixer/issues/769#issuecomment-304960507)

This is likely a problem in either Envoy's Mixer filter or the mixerclient itself. Mixer just blindly pushes the data we're provided to the metric backend, these missing stats seem to indicate that `Report` calls aren't being made to the mixer by Envoy when it sees a 500.

---

@douglas-reid commented on [Tue May 30 2017](https://github.com/istio/mixer/issues/769#issuecomment-304987349)

@qiwzhang any ideas what might cause this related to the filter chain?

**Comment by qiwzhang** [comment]
@esnible could you test it with latest Istio (0.2.6)?   As long as fault fitler is injected after mixer filter, it should work.   I just checked,  now it is injected after.

https://github.com/istio/pilot/blob/master/proxy/envoy/testdata/lds-v0-fault.json.golden#L184
