### ISSUE TITLE
Elevate common request headers to attributes

### ISSUE THREAD

**Issue by geeknoid** [istio/mixerclient#177]
We need to move common request headers to be first class attributes in order to improve cache efficiency. If the Mixer references any request headers during a Check call, the cache entry ends up being invalidated whenever any request header changes, which is the normal case. This effect completely neutralizes the existing cache.

**Comment by qiwzhang** [comment]
This should be short team solution.  It will cause data duplication.  Long team solution is to support string map subkey in ReferencedAttributes.

**Comment by geeknoid** [comment]
This can be the long term solution when it is paired with issue #178

**Comment by mandarjog** [comment]
related to Mixer issue of https://github.com/istio/mixer/issues/1099

**Comment by geeknoid** [comment]
Since we now handle individual request headers correctly, no need for this.
