### ISSUE TITLE
Add Mixer report attributes for requests rejected by Envoy proxy

### ISSUE THREAD

**Issue by qiwzhang** [istio/mixerclient#252]
1) it is not in the attribute list, should add it
2) It is only used for tcp now.   HTTP is using response.code.  Should change code to use check.status if Check fail.  Not to use response.code

**Comment by qiwzhang** [comment]
check.error_code and error_message were added to the global dictionary.   Waiting for istio/istio to pick up the changes from istio/api

**Comment by qiwzhang** [comment]
These attributes are trying to capture why requests rejected by Envoy.   Mixer check is just one of reasons. There could be many other reasons (https://github.com/envoyproxy/envoy/blob/master/include/envoy/request_info/request_info.h#L16)

We should not call these attributes as "check.*".    we should call them as followings:
* request.proxy_error:  string to display proxy error message,  Mixer check error will be here too

* request.proxy_error_code:  as int32,   to category the errors,  error message may contain detail error.  
   how to define error code? rpc.status_code?

* request.proxy_error_by, as string, such as by_mixer_check,  or by_auth,  or by_fault_injection, or by_envoy_internal?

@geeknoid @kyessenov @douglas-reid @mandarjog What do you think?

**Comment by geeknoid** [comment]
I don't think we want to specify "proxy" vs "mixer" in the attributes. This would imply that policies can be evaluated in Mixer in the report path which depend on who rejected a request, and that doesn't feel right to me.

**Comment by qiwzhang** [comment]
Wouldn't it be useful to use different tables or graphs to display number of requests rejected "by_mixer" or "by_auth", or "by_envoy_internal (due to upstream connection time out, etc)"?

**Comment by geeknoid** [comment]
​I think I'd be happier if we had a single attribute that indicated the
cause of a check rejection as a logical thing rather than a component thing.

So a single attribute that says what lead to the request being rejected,
and not what component rejected the request.​

**Comment by kyessenov** [comment]
I think we need to reuse existing check return statuses for proxy error
status. That would align with the position that mixer is an extended filter
chain in envoy. We may need to add more status codes than the standard RPC
provides.

Please also consider whether we need to sanitize some details from the
errors, or mixer can be trusted to perform sanitization afterwards.

**Comment by qiwzhang** [comment]
OK,  we will keep the original plan to use following attributes:

check.error_message: a string for error message from mixer check.  Also generate meaningful error for envoy internal errors.

check.error_code:  rpc.status_code if from mixer_check.  INTERNAL for other envoy internal errors.
