### ISSUE TITLE
Provide statistics for check and report latencies as histograms

### ISSUE THREAD

**Issue by JimmyCYJ** [istio/mixerclient#324]
Add Check/Report latency stats as histograms.

**Comment by qiwzhang** [comment]
I think it can be implemented at proxy, use a timer to wrap around the check/report call.   Mixerclient doesn't need to do anything.   So please move this issue to proxy.

**Comment by JimmyCYJ** [comment]
I have created another issue https://github.com/istio/proxy/issues/893. I am going to close this one. Thanks.

**Comment by JimmyCYJ** [comment]
The Mixer stats commits are reverted in #[961](https://github.com/istio/proxy/pull/961) due to a segmentation fault issue. Will be checked in once that issue is solved. Reopen this issue for tracking.
