### ISSUE TITLE
Add trace spans for client

### ISSUE THREAD

**Issue by douglas-reid** [istio/mixerclient#405]
For the distributed tracing features of Istio, we want to have mixerclient spans in the generated trace data. This would help with a number of debug-ability related items:

- better understanding caching
- better understanding perf of client library
- better understanding impact of network

cc: @rshriram

**Comment by geeknoid** [comment]
Issue moved to [istio/proxy #1193](https://github.com/istio/proxy/issues/1193) via [**ZenHub**](https://www.zenhub.com/)
