### ISSUE TITLE
Mixer client needs retry behavior

### ISSUE THREAD

**Issue by geeknoid** [istio/mixerclient#439]
Mixer client needs retry semantics around all calls to Mixer.

**Comment by ldemailly** [comment]
reminder: this repo is dead (you reviewed the diff that moved the code to proxy)

**Comment by geeknoid** [comment]
Issue moved to [istio/proxy #1192](https://github.com/istio/proxy/issues/1192) via [**ZenHub**](https://www.zenhub.com/)
