### ISSUE TITLE
Update copyright messages

### ISSUE THREAD

**Issue by geeknoid** [istio/mixerclient#54]
Please update all copyright messages in the repo to

Copyright XXX Istio Authors

**Comment by qiwzhang** [comment]
Here is the current one

Copyright 2017 Istio Authors. All Rights Reserved.

What need to be changed?  @geeknoid

**Comment by geeknoid** [comment]
WHen I search for Google in the mixerclient repo, I find 13 matches. I
think all these need to be converted.

**Comment by chowchow316** [comment]
Solved via #55
