### ISSUE TITLE
Support automatic dictionary fallback to recover gracefully from dictionary mismatches

### ISSUE THREAD

**Issue by geeknoid** [istio/mixerclient#80]
We should have support in mixerclient to recognize that the Mixer is using an older dictionary. Whenever this happens, the mixerclient would switch to using the V1 dictionary from that point forward (until the process is restarted that is). So a single Mixer instance not having been upgraded to the latest dictionary will lead to using an older dictionary, which would reduce overall compression, but would avoid a dictionary-related outage.

Doing this effectively means we can upgrade the dictionary in the client and mixer independently, they don't need to be in sync.

**Comment by qiwzhang** [comment]
@geeknoid  what is the error code and error string from mixer for global dictionary out of sync problem?

**Comment by geeknoid** [comment]
How about the RPC call fails with a status code of OUT_OF_RANGE and status message whch contains "invalid global dictionary index". The actual message will include the index # in there. If you see this failure, you revert back to the V1 dictionary. If you get this error when you're already using the V1 dictionary, then things are in a bad state and we need to panic.

**Comment by geeknoid** [comment]
Can this issue be closed?
